name = "parramatta-weather"
main = "src/index.ts"
compatibility_date = "2023-02-07"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[placement]
mode = "smart"

[vars]
# The necessary secrets are:
# - VALID_BEARER_TOKEN - the authentication token that gets verified for each request
# - WW_API_KEY - the Willy Weather API key